#include "album_art.h"
#include "enrichment.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <curl/curl.h>
#include <json-c/json.h>
#include <stdlib.h>
#include "version.h"
#include "platform.h"
void SbAlbumArtResultInit(SbAlbumArtResult*r){memset(r,0,sizeof(*r));r->status=SB_LOOKUP_IDLE;snprintf(r->provider,sizeof(r->provider),"Cover Art Archive");snprintf(r->reason,sizeof(r->reason),"idle");}
int SbCoverArtHttpStatus(long s,int c){if(c!=CURLE_OK)return SB_LOOKUP_ERROR;if(s==200)return SB_LOOKUP_AVAILABLE;if(s==404)return SB_LOOKUP_NO_MATCH;if(s==429||s>=500)return SB_LOOKUP_UNAVAILABLE;return SB_LOOKUP_ERROR;}
bool SbAlbumArtMimeSupported(const char*m){return m&&(!strcasecmp(m,"image/jpeg")||!strcasecmp(m,"image/png")||!strcasecmp(m,"image/webp"));}
bool SbAlbumArtFilename(const char*id,const char*m,char*out,size_t n){if(!id||!*id||!out||n==0)return false;for(const unsigned char*p=(const unsigned char*)id;*p;p++)if(!isalnum(*p)&&*p!='-')return false;const char*e=!m?"jpg":strstr(m,"png")?"png":strstr(m,"webp")?"webp":"jpg";int z=snprintf(out,n,"%s.%s",id,e);return z>0&&(size_t)z<n;}
static const char*str(json_object*o,const char*k){json_object*v=NULL;return json_object_object_get_ex(o,k,&v)&&json_object_is_type(v,json_type_string)?json_object_get_string(v):"";}
bool SbCoverArtParse(const char*j,const char*release,SbAlbumArtResult*r){SbAlbumArtResultInit(r);snprintf(r->releaseId,sizeof(r->releaseId),"%s",release?release:"");json_object*root=json_tokener_parse(j),*images=NULL;if(!root||!json_object_object_get_ex(root,"images",&images)||!json_object_is_type(images,json_type_array)){if(root)json_object_put(root);r->status=SB_LOOKUP_ERROR;return false;}json_object*best=NULL;for(size_t i=0;i<json_object_array_length(images);i++){json_object*x=json_object_array_get_idx(images,i),*front=NULL;if(json_object_object_get_ex(x,"front",&front)&&json_object_get_boolean(front)){best=x;break;}}if(!best){r->status=SB_LOOKUP_NO_MATCH;json_object_put(root);return false;}json_object*t=NULL;if(json_object_object_get_ex(best,"thumbnails",&t)){const char*u=str(t,"500");if(!*u)u=str(t,"large");snprintf(r->sourceUrl,sizeof(r->sourceUrl),"%s",u);}if(!r->sourceUrl[0])snprintf(r->sourceUrl,sizeof(r->sourceUrl),"%s",str(best,"image"));if(!r->sourceUrl[0]){r->status=SB_LOOKUP_ERROR;json_object_put(root);return false;}r->status=SB_LOOKUP_AVAILABLE;json_object_put(root);return true;}

typedef struct { unsigned char *data; size_t length; bool overflow; } ArtBuffer;
static size_t artWrite(char*p,size_t s,size_t n,void*u){ArtBuffer*b=u;size_t add=s*n;if(add>SB_ART_MAX_BYTES-b->length){b->overflow=true;return 0;}void*q=realloc(b->data,b->length+add+1);if(!q)return 0;b->data=q;memcpy(b->data+b->length,p,add);b->length+=add;b->data[b->length]=0;return add;}
static bool fetch(const char*url,ArtBuffer*b,long*status,char**type){CURL*c=curl_easy_init();if(!c)return false;curl_easy_setopt(c,CURLOPT_URL,url);curl_easy_setopt(c,CURLOPT_USERAGENT,PROGRAM_NAME "/" VERSION " (https://github.com/signalbox-player/signalbox)");curl_easy_setopt(c,CURLOPT_FOLLOWLOCATION,1L);curl_easy_setopt(c,CURLOPT_MAXREDIRS,5L);curl_easy_setopt(c,CURLOPT_TIMEOUT,15L);curl_easy_setopt(c,CURLOPT_CONNECTTIMEOUT,5L);curl_easy_setopt(c,CURLOPT_WRITEFUNCTION,artWrite);curl_easy_setopt(c,CURLOPT_WRITEDATA,b);CURLcode code=curl_easy_perform(c);curl_easy_getinfo(c,CURLINFO_RESPONSE_CODE,status);if(type){char*t=NULL;curl_easy_getinfo(c,CURLINFO_CONTENT_TYPE,&t);*type=t?strdup(t):NULL;}curl_easy_cleanup(c);return code==CURLE_OK;}
bool SbCoverArtLookup(const char*id,const char*dir,SbAlbumArtResult*r){SbAlbumArtResultInit(r);if(!id||!*id||!dir){snprintf(r->reason,sizeof(r->reason),"no_release_identity");return false;}snprintf(r->releaseId,sizeof(r->releaseId),"%s",id);char url[256];snprintf(url,sizeof(url),"https://coverartarchive.org/release/%s",id);ArtBuffer meta={0};long status=0;if(!fetch(url,&meta,&status,NULL)){r->httpStatus=status;r->status=meta.overflow?SB_LOOKUP_ERROR:SbCoverArtHttpStatus(status,CURLE_RECV_ERROR);snprintf(r->reason,sizeof(r->reason),r->status==SB_LOOKUP_UNAVAILABLE?"temporarily_unavailable":"download_error");free(meta.data);return false;}r->httpStatus=status;r->status=SbCoverArtHttpStatus(status,CURLE_OK);if(r->status!=SB_LOOKUP_AVAILABLE){snprintf(r->reason,sizeof(r->reason),r->status==SB_LOOKUP_NO_MATCH?"no_match":r->status==SB_LOOKUP_UNAVAILABLE?"temporarily_unavailable":"download_error");free(meta.data);return false;}if(!SbCoverArtParse((char*)meta.data,id,r)){snprintf(r->reason,sizeof(r->reason),r->status==SB_LOOKUP_NO_MATCH?"no_match":"download_error");free(meta.data);return false;}free(meta.data);ArtBuffer image={0};char*type=NULL;const bool fetched=fetch(r->sourceUrl,&image,&status,&type);if(!fetched||status!=200||image.overflow||!SbAlbumArtMimeSupported(type)){r->httpStatus=status;r->byteCount=image.length;r->status=fetched?SbCoverArtHttpStatus(status,CURLE_OK):SB_LOOKUP_ERROR;if(r->status==SB_LOOKUP_AVAILABLE)r->status=SB_LOOKUP_ERROR;snprintf(r->reason,sizeof(r->reason),fetched&&status==200&&!image.overflow&&!SbAlbumArtMimeSupported(type)?"unsupported_format":r->status==SB_LOOKUP_UNAVAILABLE?"temporarily_unavailable":"download_error");free(type);free(image.data);return false;}r->httpStatus=status;r->byteCount=image.length;snprintf(r->mimeType,sizeof(r->mimeType),"%s",type);free(type);char name[96];if(!SbAlbumArtFilename(id,r->mimeType,name,sizeof(name))){free(image.data);r->status=SB_LOOKUP_ERROR;snprintf(r->reason,sizeof(r->reason),"download_error");return false;}char*path=SbPlatformJoinPath(dir,name);char*tmp=path?malloc(strlen(path)+5):NULL;if(!path||!tmp){free(path);free(tmp);free(image.data);r->status=SB_LOOKUP_ERROR;snprintf(r->reason,sizeof(r->reason),"download_error");return false;}sprintf(tmp,"%s.tmp",path);FILE*f=fopen(tmp,"wb");bool ok=f&&fwrite(image.data,1,image.length,f)==image.length&&fflush(f)==0&&fclose(f)==0;if(f&&!ok)fclose(f);if(ok)ok=SbPlatformAtomicReplace(tmp,path);remove(tmp);if(ok){snprintf(r->cachedPath,sizeof(r->cachedPath),"%s",path);snprintf(r->reason,sizeof(r->reason),"available");}else{r->status=SB_LOOKUP_ERROR;snprintf(r->reason,sizeof(r->reason),"download_error");}free(path);free(tmp);free(image.data);return ok;}
