#include "enrichment_cache.h"
#include "enrichment.h"
#include "platform.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <json-c/json.h>

static void entryFree (SbCacheEntry *e) { free(e->provider); free(e->key); free(e->payload); memset(e,0,sizeof(*e)); }
void SbPersistentCacheInit (SbPersistentCache *c, char *path) { memset(c,0,sizeof(*c)); c->path=path; }
void SbPersistentCacheDestroy (SbPersistentCache *c) { for(size_t i=0;i<c->count;i++) entryFree(&c->entries[i]); free(c->entries); free(c->path); memset(c,0,sizeof(*c)); }
bool SbCacheStatePersistent (int s) { return s==SB_LOOKUP_AVAILABLE || s==SB_LOOKUP_INSTRUMENTAL || s==SB_LOOKUP_NO_MATCH; }
time_t SbCacheTtl (SbCacheKind kind, int state) { const time_t day=24*60*60; if(state==SB_LOOKUP_NO_MATCH) return kind==SB_CACHE_ART?3*day:7*day; return 60*day; }
static bool reserve(SbPersistentCache*c){if(c->count<c->capacity)return true;size_t n=c->capacity?c->capacity*2:64;if(n>SB_CACHE_MAX_ENTRIES)n=SB_CACHE_MAX_ENTRIES;if(n<=c->count)return false;void*p=realloc(c->entries,n*sizeof(*c->entries));if(!p)return false;c->entries=p;c->capacity=n;return true;}
static const char *js(json_object*o,const char*k){json_object*v=NULL;return json_object_object_get_ex(o,k,&v)&&json_object_is_type(v,json_type_string)?json_object_get_string(v):NULL;}
bool SbPersistentCacheLoad(SbPersistentCache*c,time_t now){if(!c->path)return false;FILE*f=fopen(c->path,"rb");if(!f)return false;fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);if(n<=0||n>16*1024*1024){fclose(f);return false;}char*b=malloc((size_t)n+1);if(!b||fread(b,1,(size_t)n,f)!=(size_t)n){free(b);fclose(f);return false;}b[n]=0;fclose(f);json_object*r=json_tokener_parse(b);free(b);json_object*v=NULL,*a=NULL;if(!r||!json_object_object_get_ex(r,"schema_version",&v)||json_object_get_int(v)!=SB_CACHE_SCHEMA_VERSION||!json_object_object_get_ex(r,"entries",&a)||!json_object_is_type(a,json_type_array)){if(r)json_object_put(r);return false;}for(size_t i=0;i<json_object_array_length(a)&&c->count<SB_CACHE_MAX_ENTRIES;i++){json_object*o=json_object_array_get_idx(a,i),*x=NULL;const char*p=js(o,"provider"),*k=js(o,"key"),*payload=js(o,"payload");if(!p||!k||!payload)continue;json_object_object_get_ex(o,"state",&x);int state=json_object_get_int(x);json_object_object_get_ex(o,"fetched",&x);time_t fetched=(time_t)json_object_get_int64(x);json_object_object_get_ex(o,"kind",&x);int kind=json_object_get_int(x);if(!SbCacheStatePersistent(state)||now-fetched>SbCacheTtl((SbCacheKind)kind,state)||!reserve(c))continue;SbCacheEntry*e=&c->entries[c->count++];*e=(SbCacheEntry){strdup(p),strdup(k),strdup(payload),state,fetched,fetched};if(!e->provider||!e->key||!e->payload){entryFree(e);c->count--;}}json_object_put(r);return true;}
const SbCacheEntry*SbPersistentCacheGet(SbPersistentCache*c,const char*p,const char*k,SbCacheKind kind,time_t now){for(size_t i=0;i<c->count;i++){SbCacheEntry*e=&c->entries[i];if(!strcmp(e->provider,p)&&!strcmp(e->key,k)){if(now-e->fetched>SbCacheTtl(kind,e->state))return NULL;e->used=now;return e;}}return NULL;}
bool SbPersistentCachePut(SbPersistentCache*c,const char*p,const char*k,int state,const char*payload,SbCacheKind kind,time_t now){(void)kind;if(!SbCacheStatePersistent(state)||!p||!k||!payload)return false;for(size_t i=0;i<c->count;i++)if(!strcmp(c->entries[i].provider,p)&&!strcmp(c->entries[i].key,k)){SbCacheEntry*e=&c->entries[i];char*q=strdup(payload);if(!q)return false;free(e->payload);e->payload=q;e->state=state;e->fetched=e->used=now;return true;}if(c->count==SB_CACHE_MAX_ENTRIES){size_t oldest=0;for(size_t i=1;i<c->count;i++)if(c->entries[i].used<c->entries[oldest].used)oldest=i;entryFree(&c->entries[oldest]);c->entries[oldest]=c->entries[--c->count];}if(!reserve(c))return false;SbCacheEntry*e=&c->entries[c->count++];*e=(SbCacheEntry){strdup(p),strdup(k),strdup(payload),state,now,now};return e->provider&&e->key&&e->payload;}
bool SbPersistentCacheWrite(SbPersistentCache*c){if(!c->path)return false;json_object*r=json_object_new_object(),*a=json_object_new_array();json_object_object_add(r,"schema_version",json_object_new_int(SB_CACHE_SCHEMA_VERSION));json_object_object_add(r,"entries",a);for(size_t i=0;i<c->count;i++){SbCacheEntry*e=&c->entries[i];json_object*o=json_object_new_object();json_object_object_add(o,"provider",json_object_new_string(e->provider));json_object_object_add(o,"key",json_object_new_string(e->key));json_object_object_add(o,"state",json_object_new_int(e->state));json_object_object_add(o,"fetched",json_object_new_int64(e->fetched));json_object_object_add(o,"payload",json_object_new_string(e->payload));json_object_object_add(o,"kind",json_object_new_int(strstr(e->provider,"cover")?SB_CACHE_ART:strstr(e->provider,"lrclib")?SB_CACHE_LYRICS:SB_CACHE_METADATA));json_object_array_add(a,o);}const char*s=json_object_to_json_string_ext(r,JSON_C_TO_STRING_PRETTY);size_t z=strlen(c->path)+5;char*t=malloc(z);if(!t){json_object_put(r);return false;}snprintf(t,z,"%s.tmp",c->path);FILE*f=fopen(t,"wb");bool ok=f&&fwrite(s,1,strlen(s),f)==strlen(s)&&fflush(f)==0&&fclose(f)==0;if(f&&!ok)fclose(f);if(ok)ok=SbPlatformAtomicReplace(t,c->path);remove(t);free(t);json_object_put(r);return ok;}
